VehicleNames = {
	[15801] = {name = "US Semitruck", categ = "Truck", path = "us_truck"},
	[17886] = {name = "Front Loader", categ = "Heavy machinery", path = "frontloader"},
	[1907] = {name = "Small Crane", categ = "Heavy machinery", path = "mobile_crane"},
	[19392] = {name = "Small Truck", categ = "Truck", path = "truck_white"},
	[1981] = {name = "Small Excavator", categ = "Heavy machinery", path = "small_excavator"},
	[23865] = {name = "Medium Boat", categ = "Boat", path = "mediumboat"},
	[2861] = {name = "Small Boat", categ = "Boat", path = "smallboat"},
	[3043] = {name = "Microcar", categ = "Car", path = "microcar"},
	[43] = {name = "Basket Lift", categ = "Heavy machinery", path = "basketlift"},
	[4665] = {name = "Seidel", categ = "Car", path = "seidel_blue"},
	[4710] = {name = "Station Wagon", categ = "Car", path = "station_wagon_blue"},
	[4876] = {name = "Dump Truck", categ = "Heavy machinery", path = "dump_truck"},
	[4997] = {name = "Big Excavator", categ = "Heavy machinery", path = "big_excavator"},
	[5148] = {name = "Hummer", categ = "Car", path = "path_racer"},
	[5625] = {name = "Muscle Car", categ = "Car", path = "musclecar_green"},
	[63464] = {name = "Speed Boat", categ = "Boat", path = "speedboat"},
	[7444] = {name = "Monster Truck", categ = "Car", path = "monstertruck"},
	[7601] = {name = "Red Pickup", categ = "Car", path = "pickup_red"},
	[9774] = {name = "Wood Boat", categ = "Boat", path = "woodboat"},
	-------------------------
	[10994] = {name = "Van", categ = "Car", path = ""},
	[12163] = {name = "EU Semitruck", categ = "Truck", path = ""},
	[12212] = {name = "Big Forklift", categ = "Heavy machinery", path = ""},
	[2206] = {name = "Small Forklift", categ = "Heavy machinery", path = ""},
	[4436] = {name = "Saloon Car", categ = "Car", path = ""},
	[4448] = {name = "Defender", categ = "Car", path = ""},
	[578] = {name = "Fishing Boat", categ = "Boat", path = ""},
	[6938] = {name = "SUV", categ = "Car", path = ""},
	[81256] = {name = "Yacht", categ = "Boat", path = ""},
	-------------------------
	[12930] = {name = "Ramp Truck", categ = "Truck", path = ""},
	[1994] = {name = "Tractor", categ = "Heavy machinery", path = ""},
	[3284] = {name = "Skylift", categ = "Heavy machinery", path = ""},
	[3412] = {name = "Sport Car (Green)", categ = "Car", path = ""},
	[4106] = {name = "Modern S. Wagon", categ = "Car", path = ""},
	[4927] = {name = "Castanet", categ = "Car", path = ""},
	[5048] = {name = "Racing Car", categ = "Car", path = ""},
	-------------------------
	[2060] = {name = "Jacobi", categ = "Car", path = ""},
	[2084] = {name = "Jacobi (Lights)", categ = "Car", path = ""},
	[3408] = {name = "Sport Car (Pink)", categ = "Car", path = ""},
	-------------------------
	[11299] = {name = "Van LTS (New)", categ = "Car", path = ""},
	[11809] = {name = "Tank", categ = "Military", path = ""},
	[4772] = {name = "Tank ATV", categ = "Military", path = ""},
	-------------------------
	[21064] = {name = "Tug Boat", categ = "Boat", path = ""},
	[2482] = {name = "Red Yacht", categ = "Boat", path = ""},
	-------------------------
	[18922] = {name = "Crane Truck", categ = "Heavy machinery", path = ""},
	[4447] = {name = "Saloon Car (RV)", categ = "Car", path = ""},
	-------------------------
	[10167] = {name = "Van FBI", categ = "Car", path = ""},
	[10747] = {name = "Military Truck", categ = "Military", path = ""},
	[15876] = {name = "Mayhem Semitruck", categ = "Truck", path = ""},
	[20574] = {name = "Boat LTS (New)", categ = "Boat", path = ""},
	[2074] = {name = "Electric Forklift", categ = "Heavy machinery", path = ""},
	[2191] = {name = "Bumper Car", categ = "Car", path = ""},
	[5818] = {name = "Cement Truck", categ = "Heavy machinery", path = ""},
	[6889] = {name = "Armed Van", categ = "Military", path = ""},
	[8822] = {name = "Van Flatbed", categ = "Car", path = ""},
	-------------------------
	[91] = {name = "Heavy Duty Truck", categ = "Military", path = ""},
	[4914] = {name = "Plow Truck", categ = "Truck", path = ""},
	[4445] = {name = "Seidel", categ = "Car", path = ""}, -- w/Open trunk
	[3764] = {name = "Swan Boat", categ = "Boat", path = ""},
	[19463] = {name = "Boat LTS (Old)", categ = "Boat", path = ""},
	[11481] = {name = "Van LTS (Old)", categ = "Car", path = ""},
	[10544] = {name = "Van (MOVE)", categ = "Car", path = ""},
	-------------------------
	[1253] = {name = "Golf Cart", categ = "Car", path = ""},
	[14066] = {name = "Helicopter", categ = "Military", path = ""},
	[14120] = {name = "Heavy Duty Truck", categ = "Military", path = ""},
	[14934] = {name = "Truxterminator", categ = "Military", path = ""},
	[150214] = {name = "Big Cargo Boat", categ = "Boat", path = ""},
	[21295] = {name = "Bus", categ = "Truck", path = ""},
	[2182] = {name = "Small Boat", categ = "Boat", path = ""},
	[225] = {name = "Motorbike", categ = "Car", path = ""},
	[3496] = {name = "Small Crane", categ = "Heavy machinery", path = ""},
	[4358] = {name = "Defender", categ = "Car", path = ""},
	[4468] = {name = "Taxi", categ = "Car", path = ""},
	[4808] = {name = "Castanet (Broken)", categ = "Car", path = ""},
	[5289] = {name = "Small Boat", categ = "Boat", path = ""},
	[5331] = {name = "Small Boat", categ = "Boat", path = ""},
	[5494] = {name = "Police SUV", categ = "Car", path = ""},
	[7794] = {name = "Monster Truck", categ = "Car", path = ""},
	-------------------------
	[17647] = {name = "Ice Cream Van", categ = "Car", path = "icevan2"},
	[15851] = {name = "Hot Dog Truck", categ = "Car", path = "hotvan"},
}

RobotNames = {
	[1517] = {name = "Spider Mech", path = ""},
	[170] = {name = "Cute Bot", path = ""},
	[22] = {name = "Alarm", path = ""},
	[319] = {name = "Prototype 1", path = ""},
	[31] = {name = "Chase", path = ""},
	[377] = {name = "Prototype 2", path = ""},
	[404] = {name = "Prototype 3", path = ""},
	[658] = {name = "Flamethrower", path = ""},
	[671] = {name = "Rocket Launcher", path = ""},
	[742] = {name = "Machine Gun", path = ""},
	[805] = {name = "Basic", path = ""},
}
